import { and, eq, isNotNull, isNull } from "drizzle-orm";
import { z } from "zod";
import { passwordVaultEntries } from "../../drizzle/schema";
import { requireCurrentAccount } from "../account-context";
import { getDb, getOwnedClient } from "../db";
import { decryptVaultPassword, encryptVaultPassword } from "../password-vault-crypto";
import { resolveProgramClientOption } from "../program-client-options";
import { publicProcedure, router } from "../_core/trpc";

const clientScope = z.object({ clientId: z.number().int().positive() });
const vaultInput = z.object({ category: z.string().trim().min(2).max(100).default("Autre"), platformName: z.string().trim().min(2).max(180), platformUrl: z.string().trim().max(1200).default(""), email: z.string().trim().max(320).default(""), phone: z.string().trim().max(80).default(""), username: z.string().trim().max(320).default(""), password: z.string().min(1).max(500) });
const purgeAfterThirtyDays = () => new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
const listed = (entry: typeof passwordVaultEntries.$inferSelect) => ({ id: entry.id, clientId: entry.clientId, category: entry.category, platformName: entry.platformName, platformUrl: entry.platformUrl, email: entry.email, phone: entry.phone, username: entry.username, updatedAt: entry.updatedAt });
async function ownedScope(request: Parameters<typeof requireCurrentAccount>[0], clientId: number) { const account = await requireCurrentAccount(request); if (!(await getOwnedClient(account.id, clientId))) throw new Error("Client introuvable."); return account; }

export const passwordVaultRouter = router({
  list: publicProcedure.input(clientScope).query(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entries = await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNull(passwordVaultEntries.deletedAt))); return entries.map(listed); }),
  archived: publicProcedure.input(clientScope).query(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entries = await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNotNull(passwordVaultEntries.deletedAt))); return entries.map(entry => ({ ...listed(entry), deletedAt: entry.deletedAt, purgeAfter: entry.purgeAfter })); }),
  reveal: publicProcedure.input(clientScope.extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entry = (await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNull(passwordVaultEntries.deletedAt))).limit(1))[0]; if (!entry) throw new Error("Accès introuvable."); return { password: decryptVaultPassword(account.id, input.clientId, entry) }; }),
  create: publicProcedure.input(vaultInput.extend({ clientId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const category = await resolveProgramClientOption(db, account.id, "vaultCategory", input.category); const sealed = encryptVaultPassword(account.id, input.clientId, input.password); await db.insert(passwordVaultEntries).values({ accountId: account.id, clientId: input.clientId, category: category.label, platformName: input.platformName, platformUrl: input.platformUrl, email: input.email, phone: input.phone, username: input.username, ...sealed }); return { success: true } as const; }),
  update: publicProcedure.input(z.object({ id: z.number().int().positive(), clientId: z.number().int().positive(), entry: vaultInput })).mutation(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const category = await resolveProgramClientOption(db, account.id, "vaultCategory", input.entry.category); const sealed = encryptVaultPassword(account.id, input.clientId, input.entry.password); await db.update(passwordVaultEntries).set({ category: category.label, platformName: input.entry.platformName, platformUrl: input.entry.platformUrl, email: input.entry.email, phone: input.entry.phone, username: input.entry.username, ...sealed }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
  archive: publicProcedure.input(clientScope.extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); await db.update(passwordVaultEntries).set({ deletedAt: new Date(), purgeAfter: purgeAfterThirtyDays() }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
  restore: publicProcedure.input(clientScope.extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await ownedScope(ctx.req, input.clientId); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); await db.update(passwordVaultEntries).set({ deletedAt: null, purgeAfter: null }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), eq(passwordVaultEntries.clientId, input.clientId), isNotNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
});
