import { and, eq, isNotNull, isNull } from "drizzle-orm";
import { z } from "zod";
import { passwordVaultEntries } from "../../drizzle/schema";
import { requireCurrentAccount } from "../account-context";
import { getDb } from "../db";
import { decryptVaultPassword, encryptVaultPassword } from "../password-vault-crypto";
import { publicProcedure, router } from "../_core/trpc";

const vaultInput = z.object({ platformName: z.string().trim().min(2).max(180), platformUrl: z.string().trim().max(1200).default(""), email: z.string().trim().max(320).default(""), phone: z.string().trim().max(80).default(""), username: z.string().trim().max(320).default(""), password: z.string().min(1).max(500) });
const purgeAfterThirtyDays = () => new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
const listed = (entry: typeof passwordVaultEntries.$inferSelect) => ({ id: entry.id, platformName: entry.platformName, platformUrl: entry.platformUrl, email: entry.email, phone: entry.phone, username: entry.username, updatedAt: entry.updatedAt });

export const passwordVaultRouter = router({
  list: publicProcedure.query(async ({ ctx }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entries = await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.accountId, account.id), isNull(passwordVaultEntries.deletedAt))); return entries.map(listed); }),
  archived: publicProcedure.query(async ({ ctx }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entries = await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.accountId, account.id), isNotNull(passwordVaultEntries.deletedAt))); return entries.map(entry => ({ ...listed(entry), deletedAt: entry.deletedAt, purgeAfter: entry.purgeAfter })); }),
  reveal: publicProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const entry = (await db.select().from(passwordVaultEntries).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), isNull(passwordVaultEntries.deletedAt))).limit(1))[0]; if (!entry) throw new Error("Accès introuvable."); return { password: decryptVaultPassword(account.id, entry) }; }),
  create: publicProcedure.input(vaultInput).mutation(async ({ ctx, input }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const sealed = encryptVaultPassword(account.id, input.password); await db.insert(passwordVaultEntries).values({ accountId: account.id, platformName: input.platformName, platformUrl: input.platformUrl, email: input.email, phone: input.phone, username: input.username, ...sealed }); return { success: true } as const; }),
  update: publicProcedure.input(z.object({ id: z.number().int().positive(), entry: vaultInput })).mutation(async ({ ctx, input }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); const sealed = encryptVaultPassword(account.id, input.entry.password); await db.update(passwordVaultEntries).set({ platformName: input.entry.platformName, platformUrl: input.entry.platformUrl, email: input.entry.email, phone: input.entry.phone, username: input.entry.username, ...sealed }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), isNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
  archive: publicProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); await db.update(passwordVaultEntries).set({ deletedAt: new Date(), purgeAfter: purgeAfterThirtyDays() }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), isNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
  restore: publicProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const account = await requireCurrentAccount(ctx.req); const db = await getDb(); if (!db) throw new Error("La base de données est indisponible."); await db.update(passwordVaultEntries).set({ deletedAt: null, purgeAfter: null }).where(and(eq(passwordVaultEntries.id, input.id), eq(passwordVaultEntries.accountId, account.id), isNotNull(passwordVaultEntries.deletedAt))); return { success: true } as const; }),
});
