/** Panneaux visuels indépendants du flux de transfert. */

import { Download, FileJson, FileSpreadsheet, ShieldCheck, Upload } from "lucide-react";
import type { ChangeEvent } from "react";

type ClientItem = { id: number; fullName: string; status: string | null };

export function ExportPanel({ format, setFormat, activeClientId, clients, selected, toggle, pending, onExport }: { format: "json" | "xlsx"; setFormat: (format: "json" | "xlsx") => void; activeClientId: number; clients: ClientItem[]; selected: number[]; toggle: (id: number) => void; pending: boolean; onExport: (scope: "active" | "selected" | "all") => void }) {
  return <section className="rounded-2xl border border-[#d5dfdc] bg-white p-6 shadow-[0_10px_28px_rgba(16,42,67,0.04)]"><div className="flex items-center gap-3"><Download className="text-[#0f766e]" /><div><h2 className="font-serif text-3xl">Exporter les dossiers</h2><p className="mt-1 text-sm text-[#627785]">Les fichiers contiennent une vue d’ensemble et des feuilles distinctes par rubrique.</p></div></div><div className="mt-6 flex gap-2"><button onClick={() => setFormat("xlsx")} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-bold ${format === "xlsx" ? "border-[#0f766e] bg-[#e6f3ed] text-[#0f766e]" : "border-[#d5dfdc]"}`}><FileSpreadsheet size={16} /> Excel officiel</button><button onClick={() => setFormat("json")} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-bold ${format === "json" ? "border-[#0f766e] bg-[#e6f3ed] text-[#0f766e]" : "border-[#d5dfdc]"}`}><FileJson size={16} /> Archive JSON</button></div>{activeClientId > 0 ? <button disabled={pending} onClick={() => onExport("active")} className="mt-4 rounded-lg bg-[#102a43] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Exporter le client ouvert</button> : null}<div className="mt-5 max-h-64 space-y-2 overflow-y-auto rounded-xl border border-[#e3ebe8] bg-[#fbfdfc] p-3">{clients.map(client => <label key={client.id} className="flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-white"><input checked={selected.includes(client.id)} onChange={() => toggle(client.id)} type="checkbox" className="accent-[#0f766e]" /><span className="flex-1 text-sm font-bold">{client.fullName}</span><span className="text-xs text-[#627785]">{client.status}</span></label>)}{clients.length === 0 ? <p className="p-3 text-sm text-[#627785]">Aucun dossier à exporter.</p> : null}</div><div className="mt-4 flex flex-wrap gap-3"><button disabled={!selected.length || pending} onClick={() => onExport("selected")} className="rounded-lg bg-[#0f766e] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Exporter la sélection</button><button disabled={!clients.length || pending} onClick={() => onExport("all")} className="rounded-lg border border-[#cfdad7] bg-white px-4 py-2.5 text-sm font-bold text-[#102a43] disabled:opacity-50">Exporter tous mes clients</button></div></section>;
}

export function ImportPanel({ onFile, fileName, isImporting, ready, onCommit }: { onFile: (event: ChangeEvent<HTMLInputElement>) => void; fileName: string; isImporting: boolean; ready: boolean; onCommit: () => void }) { return <section className="rounded-2xl border border-[#d5dfdc] bg-white p-6 shadow-[0_10px_28px_rgba(16,42,67,0.04)]"><div className="flex items-center gap-3"><Upload className="text-[#0f766e]" /><div><h2 className="font-serif text-3xl">Importer des dossiers</h2><p className="mt-1 text-sm text-[#627785]">Choisissez une archive JSON ou XLSX issue du système, puis contrôlez son contenu.</p></div></div><label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#bbd4cc] bg-[#f1f8f4] px-5 py-9 text-center"><Upload size={24} className="text-[#0f766e]" /><span className="mt-3 text-sm font-bold">Choisir une archive JSON ou XLSX</span><span className="mt-1 text-xs text-[#627785]">Maximum 8 Mo · aucune macro n’est exécutée</span><input onChange={onFile} type="file" accept=".json,.xlsx" className="sr-only" /></label>{fileName ? <div className="mt-5 rounded-xl border border-[#c9ded7] bg-[#eef7f3] p-4"><p className="text-sm font-bold">Archive prête : {fileName}</p><p className="mt-1 text-xs leading-5 text-[#627785]">L’import crée de nouveaux dossiers dans votre compte et ne remplace aucun dossier existant.</p><button disabled={!ready || isImporting} onClick={onCommit} className="mt-4 rounded-lg bg-[#102a43] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{isImporting ? "Importation…" : "Confirmer l’import"}</button></div> : null}</section>; }
export function TransferSecurityNotice() { return <div className="mt-6 flex items-start gap-3 rounded-xl border border-[#c6ddd5] bg-[#e9f5f0] p-5"><ShieldCheck className="mt-0.5 text-[#0f766e]" /><p className="text-sm leading-6 text-[#426c62]">Chaque archive est liée au compte actuellement connecté. Les identifiants de propriété ne sont jamais inclus dans les exports et sont ignorés lors d’un import.</p></div>; }
