import { AppSelect } from "@/components/form/app-select";
import { PageTitle, WorkspaceLayout } from "@/components/workspace-layout";
import { AccountProgramNav } from "@/features/account/account-program-nav";
import { RcCatalogueManager } from "@/features/program-settings/rc-catalogue-manager";
import { trpc } from "@/lib/trpc";
import { programReferenceRegistry, type AccountOptionKind, type ProgramReferenceDefinition } from "@shared/reference-registry";
import { registreCommerceActivities, registreCommerceFamilies } from "@shared/registre-commerce-activities";
import { ArchiveRestore, BookOpenCheck, FileSearch, FolderCog, KeyRound, ListChecks, LockKeyhole, Plus, Save, Settings2, Tag, Trash2, UsersRound } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

type ProgramStatus = { id: number; label: string; isOperational: boolean; usageCount?: number };
type ProgramOption = { id: number; code: string; label: string; usageCount?: number };
type ReferenceSummary = ProgramReferenceDefinition & { valueCount: number; usageCount: number; catalogueFamilies?: number };
type SettingsTab = "dossiers" | "listes" | "registre-rc" | "archives";

const optionSections = programReferenceRegistry.filter(reference => reference.optionKind).map(reference => ({ kind: reference.optionKind as AccountOptionKind, eyebrow: reference.group, title: reference.title, hint: reference.description }));
const tabs: { id: SettingsTab; label: string; icon: typeof FolderCog }[] = [
  { id: "dossiers", label: "Dossiers", icon: FolderCog },
  { id: "listes", label: "Listes du cabinet", icon: ListChecks },
  { id: "registre-rc", label: "Registre de commerce", icon: BookOpenCheck },
  { id: "archives", label: "Archives", icon: ArchiveRestore },
];

export function ProgramSettingsPage() {
  const utils = trpc.useUtils();
  const statuses = trpc.programSettings.clientStatuses.list.useQuery(undefined, { staleTime: 30_000 });
  const referenceRegistry = trpc.programSettings.referenceRegistry.list.useQuery(undefined, { staleTime: 30_000 });
  const [activeTab, setActiveTab] = useState<SettingsTab>("dossiers");
  const [newLabel, setNewLabel] = useState("");
  const [newOperational, setNewOperational] = useState(true);
  const [statusMessage, setStatusMessage] = useState("");
  const operationalCount = useMemo(() => (statuses.data ?? []).filter(status => status.isOperational).length, [statuses.data]);
  const refresh = async () => { await Promise.all([utils.programSettings.clientStatuses.list.invalidate(), utils.programSettings.referenceRegistry.list.invalidate(), utils.clients.list.invalidate()]); };
  const createStatus = trpc.programSettings.clientStatuses.create.useMutation({ onSuccess: async () => { setNewLabel(""); setStatusMessage("Statut ajouté."); await refresh(); } });
  const addStatus = async (event: FormEvent) => { event.preventDefault(); setStatusMessage(""); try { await createStatus.mutateAsync({ label: newLabel, isOperational: newOperational }); } catch (error) { setStatusMessage(error instanceof Error ? error.message : "Création impossible."); } };
  const references = (referenceRegistry.data ?? []) as ReferenceSummary[];
  const dossierOptions = optionSections.filter(section => ["legalForm", "clientType", "regime"].includes(section.kind));
  const organisationOptions = optionSections.filter(section => !["legalForm", "clientType", "regime"].includes(section.kind));

  return <WorkspaceLayout>
    <PageTitle eyebrow="Configuration du cabinet" title="Réglages du programme" description="Gérez les listes et le catalogue utilisés par votre cabinet." />
    <AccountProgramNav />
    <nav aria-label="Sections des réglages" className="mb-6 flex gap-1 overflow-x-auto border-b border-[#d7e0df]">{tabs.map(tab => { const Icon = tab.icon; const active = activeTab === tab.id; return <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-sm font-bold ${active ? "border-[#0b625e] text-[#0b625e]" : "border-transparent text-[#627785] hover:text-[#182b3a]"}`}><Icon size={16} />{tab.label}</button>; })}</nav>

    {activeTab === "dossiers" ? <section className="space-y-5">
      <SettingsHeader icon={<FolderCog size={19} />} eyebrow="Référentiels des dossiers" title="Statuts et informations client" text="Modifiez les valeurs réellement utilisées lors de la création et du suivi des dossiers." />
      <section className="ui-sheet p-5 sm:p-6"><div className="flex flex-col gap-4 border-b border-[#dce3dc] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="ui-label">Statuts client</p><h2 className="mt-2 font-serif text-3xl text-[#182b3a]">États des dossiers</h2></div><div className="grid grid-cols-2 gap-px border border-[#d6ded7] bg-[#d6ded7]"><Metric label="Statuts" value={String(statuses.data?.length ?? 0)} /><Metric label="Actifs" value={String(operationalCount)} tone="teal" /></div></div><div className="mt-5 grid min-w-0 gap-3 xl:grid-cols-2">{statuses.isLoading ? <LoadingLine text="Chargement des statuts…" /> : statuses.data?.map(status => <ProgramStatusRow key={status.id} status={status} onChanged={refresh} />)}</div><form onSubmit={addStatus} className="mt-5 border-l-[3px] border-[#0b625e] bg-[#f4f8f5] p-4"><p className="ui-label">Nouveau statut</p><div className="mt-3 grid min-w-0 gap-3 lg:grid-cols-[minmax(0,1fr)_220px_auto]"><input value={newLabel} onChange={event => setNewLabel(event.target.value)} required minLength={2} maxLength={60} className="ui-input min-w-0 font-semibold" placeholder="Ex. En attente" /><AppSelect value={newOperational ? "operational" : "non-operational"} onValueChange={value => setNewOperational(value === "operational")} options={[{ value: "operational", label: "Compte comme actif" }, { value: "non-operational", label: "Hors actifs" }]} /><button disabled={createStatus.isPending || !newLabel.trim()} className="ui-action disabled:opacity-60"><Plus size={17} />{createStatus.isPending ? "Ajout…" : "Ajouter"}</button></div>{statusMessage ? <Feedback message={statusMessage} /> : null}</form></section>
      <section className="grid gap-5 2xl:grid-cols-3">{dossierOptions.map(section => <ClientOptionSection key={section.kind} {...section} />)}</section>
    </section> : null}

    {activeTab === "listes" ? <section className="space-y-5"><SettingsHeader icon={<ListChecks size={19} />} eyebrow="Listes utilisées" title="Contacts et accès" text="Ces valeurs alimentent les listes déroulantes des contacts et du coffre du client." /><section className="grid gap-5 2xl:grid-cols-2">{organisationOptions.map(section => <ClientOptionSection key={section.kind} {...section} />)}</section><ReferenceControlList references={references} loading={referenceRegistry.isLoading} /></section> : null}
    {activeTab === "registre-rc" ? <RcCatalogueManager /> : null}
    {activeTab === "archives" ? <section className="space-y-5"><SettingsHeader icon={<ArchiveRestore size={19} />} eyebrow="Conservation" title="Éléments archivés" text="Les valeurs retirées restent récupérables pendant 30 jours avant la purge définitive." /><section className="ui-sheet flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="font-serif text-2xl text-[#182b3a]">Archives du cabinet</p><p className="mt-2 text-sm leading-6 text-[#63737d]">Restaurez les dossiers, contacts, statuts et valeurs administratives encore disponibles.</p></div><Link href="/archives" className="ui-action shrink-0"><ArchiveRestore size={17} /> Ouvrir les Archives</Link></section></section> : null}
  </WorkspaceLayout>;
}

function SettingsHeader({ icon, eyebrow, title, text }: { icon: React.ReactNode; eyebrow: string; title: string; text: string }) { return <div className="ui-sheet flex items-start gap-3 p-5 sm:p-6"><span className="grid h-10 w-10 shrink-0 place-items-center border border-[#b8d2c7] bg-[#eaf3ee] text-[#0b625e]">{icon}</span><div><p className="ui-label">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl text-[#182b3a]">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#63737d]">{text}</p></div></div>; }
function LoadingLine({ text }: { text: string }) { return <p className="border border-dashed border-[#cbd9d5] bg-[#f7faf6] p-4 text-sm text-[#63737d]">{text}</p>; }
function Metric({ label, value, tone = "paper" }: { label: string; value: string; tone?: "paper" | "teal" }) { return <div className={`min-w-0 p-3 ${tone === "teal" ? "bg-[#0b625e] text-white" : "bg-[#fffefa] text-[#182b3a]"}`}><p className="truncate text-[9px] font-extrabold uppercase tracking-[.1em] opacity-70">{label}</p><p className="mt-1 font-serif text-2xl">{value}</p></div>; }

function ReferenceControlList({ references, loading }: { references: ReferenceSummary[]; loading: boolean }) {
  if (loading) return <LoadingLine text="Vérification des usages…" />;
  return <section className="ui-sheet p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center border border-[#d9c483] bg-[#fff7df] text-[#87661e]"><Settings2 size={19} /></span><div><p className="ui-label">Contrôles</p><h2 className="mt-2 font-serif text-3xl text-[#182b3a]">Usage des référentiels</h2><p className="mt-1 text-sm leading-6 text-[#63737d]">Vérifiez les valeurs utilisées avant de les archiver.</p></div></div><div className="mt-5 divide-y divide-[#dce3dc] border-y border-[#dce3dc]">{references.filter(reference => reference.scope !== "utilisateur").map(reference => <div key={reference.id} className="grid gap-2 py-3 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><div className="min-w-0"><p className="font-bold text-[#182b3a]">{reference.title}</p><p className="mt-1 text-xs text-[#63737d]">{reference.mode === "administrable" ? "Valeurs modifiables dans cet espace" : "Référentiel contrôlé"}</p></div><span className="self-center text-xs font-bold text-[#526872]">{reference.valueCount} valeur(s)</span><span className="self-center text-xs font-bold text-[#0b625e]">{reference.usageCount} utilisée(s)</span></div>)}</div></section>;
}

function RcCataloguePanel({ references }: { references: ReferenceSummary[] }) {
  const [query, setQuery] = useState("");
  const normalized = query.trim().toLocaleLowerCase("fr");
  const families = useMemo(() => registreCommerceFamilies.filter(family => !normalized || `${family.code} ${family.label}`.toLocaleLowerCase("fr").includes(normalized)).slice(0, 30), [normalized]);
  const rc = references.find(reference => reference.id === "registreCommerce");
  return <section className="space-y-5"><SettingsHeader icon={<BookOpenCheck size={19} />} eyebrow="Nomenclature d’activité" title="Registre de commerce" text="Recherchez, contrôlez et mettez à jour le catalogue uniquement à partir du fichier Excel autorisé." /><section className="ui-sheet p-5 sm:p-6"><div className="grid grid-cols-3 gap-px border border-[#d8e2dc] bg-[#d8e2dc]"><Metric label="Catégories" value={String(registreCommerceFamilies.length)} /><Metric label="Activités" value={String(registreCommerceActivities.length)} tone="teal" /><Metric label="Dossiers liés" value={String(rc?.usageCount ?? 0)} /></div><label className="mt-5 flex h-11 items-center gap-2 border border-[#c7d8d3] bg-white px-3 text-[#63737d]"><FileSearch size={17} className="text-[#0b625e]" /><input value={query} onChange={event => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm text-[#182b3a] outline-none" placeholder="Rechercher une catégorie RC…" /></label><div className="mt-4 max-h-80 overflow-y-auto border-y border-[#dce3dc]">{families.map(family => <div key={family.code} className="grid grid-cols-[4.5rem_1fr_auto] gap-3 border-b border-[#e7ece8] px-1 py-3 last:border-b-0"><span className="font-serif text-xl text-[#0b625e]">{family.code}</span><span className="min-w-0 text-sm font-bold text-[#182b3a]">{family.label}</span><span className="text-xs font-semibold text-[#63737d]">{family.activityCount} activité(s)</span></div>)}{!families.length ? <p className="p-4 text-sm text-[#63737d]">Aucune catégorie ne correspond.</p> : null}</div></section><section className="border-l-[3px] border-[#d29a3e] bg-[#fff9e8] p-4 text-sm leading-6 text-[#765d27]"><p className="font-bold">Mise à jour du catalogue</p><p className="mt-1">L’ajout, la modification ou le remplacement se fera à partir d’un fichier Excel contrôlé dans cette rubrique. Les valeurs saisies librement ne seront pas acceptées.</p></section></section>;
}

function ClientOptionSection({ kind, title, eyebrow, hint }: { kind: AccountOptionKind; title: string; eyebrow: string; hint: string }) {
  const utils = trpc.useUtils(); const query = trpc.programSettings.clientOptions.list.useQuery({ kind }, { staleTime: 30_000 }); const [label, setLabel] = useState(""); const [message, setMessage] = useState(""); const refresh = async () => { await Promise.all([utils.programSettings.clientOptions.list.invalidate({ kind }), utils.programSettings.referenceRegistry.list.invalidate(), utils.clients.list.invalidate()]); }; const create = trpc.programSettings.clientOptions.create.useMutation({ onSuccess: async () => { setLabel(""); setMessage("Valeur ajoutée."); await refresh(); } }); const add = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await create.mutateAsync({ kind, label }); } catch (error) { setMessage(error instanceof Error ? error.message : "Création impossible."); } };
  return <article className="min-w-0 border-t-2 border-[#0b625e] bg-[#f7faf6] p-4"><p className="ui-label">{eyebrow}</p><h3 className="mt-2 font-serif text-2xl text-[#182b3a]">{title}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-[#63737d]">{hint}</p><div className="mt-4 space-y-2">{query.isLoading ? <p className="text-sm text-[#63737d]">Chargement…</p> : (query.data as ProgramOption[] | undefined)?.map(option => <ClientOptionRow key={option.id} option={option} onChanged={refresh} />)}</div><form onSubmit={add} className="mt-4 flex min-w-0 gap-2 border-t border-[#d9e1da] pt-4"><input value={label} onChange={event => setLabel(event.target.value)} required minLength={2} maxLength={100} placeholder="Ajouter une valeur" className="ui-input min-w-0 flex-1" /><button disabled={create.isPending || !label.trim()} className="ui-action h-11 shrink-0 px-3 disabled:opacity-60" aria-label={`Ajouter à ${title}`}><Plus size={17} /></button></form>{message ? <Feedback message={message} /> : null}</article>;
}
function ClientOptionRow({ option, onChanged }: { option: ProgramOption; onChanged: () => Promise<void> }) { const [label, setLabel] = useState(option.label); const [message, setMessage] = useState(""); const update = trpc.programSettings.clientOptions.update.useMutation({ onSuccess: async () => { setMessage("Valeur enregistrée."); await onChanged(); } }); const remove = trpc.programSettings.clientOptions.remove.useMutation({ onSuccess: async () => { await onChanged(); } }); useEffect(() => setLabel(option.label), [option.id, option.label]); const save = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await update.mutateAsync({ id: option.id, label }); } catch (error) { setMessage(error instanceof Error ? error.message : "Modification impossible."); } }; const archive = async () => { setMessage(""); try { await remove.mutateAsync({ id: option.id }); } catch (error) { setMessage(error instanceof Error ? error.message : "Archivage impossible."); } }; return <form onSubmit={save} className="min-w-0 border border-[#dfe4de] bg-[#fffefa] p-2"><div className="flex min-w-0 flex-wrap gap-2"><input value={label} onChange={event => setLabel(event.target.value)} required minLength={2} maxLength={100} className="h-11 min-w-[12rem] flex-1 border border-[#c9dad5] px-2 text-sm font-semibold text-[#182b3a] outline-none focus:border-[#0b625e]" aria-label={`Valeur ${option.label}`} /><button disabled={update.isPending} className="inline-flex h-11 items-center justify-center border border-[#9dc7bb] px-2 text-[#0b625e] disabled:opacity-60" aria-label={`Enregistrer ${option.label}`}><Save size={16} /></button><button type="button" onClick={() => void archive()} disabled={remove.isPending || Boolean(option.usageCount)} className="inline-flex h-11 items-center justify-center border border-[#efc8c3] px-2 text-[#a1433d] disabled:cursor-not-allowed disabled:opacity-40" aria-label={`Archiver ${option.label}`}><Trash2 size={16} /></button></div><p className="mt-2 text-[11px] font-semibold text-[#63737d]">Utilisée par {option.usageCount ?? 0} élément(s){option.usageCount ? " · archivage bloqué" : " · archivage autorisé"}.</p>{message ? <Feedback message={message} /> : null}</form>; }
function ProgramStatusRow({ status, onChanged }: { status: ProgramStatus; onChanged: () => Promise<void> }) { const [label, setLabel] = useState(status.label); const [isOperational, setIsOperational] = useState(status.isOperational); const [message, setMessage] = useState(""); const update = trpc.programSettings.clientStatuses.update.useMutation({ onSuccess: async () => { setMessage("Statut enregistré."); await onChanged(); } }); const remove = trpc.programSettings.clientStatuses.remove.useMutation({ onSuccess: async () => { await onChanged(); } }); useEffect(() => { setLabel(status.label); setIsOperational(status.isOperational); }, [status.id, status.label, status.isOperational]); const save = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await update.mutateAsync({ id: status.id, label, isOperational }); } catch (error) { setMessage(error instanceof Error ? error.message : "Modification impossible."); } }; const archive = async () => { setMessage(""); try { await remove.mutateAsync({ id: status.id }); } catch (error) { setMessage(error instanceof Error ? error.message : "Archivage impossible."); } }; return <form onSubmit={save} className="min-w-0 border border-[#d9e6e1] bg-[#fffefa] p-3"><div className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_210px_auto_auto]"><input value={label} onChange={event => setLabel(event.target.value)} required minLength={2} maxLength={60} className="ui-input min-w-0 font-semibold" aria-label={`Libellé du statut ${status.label}`} /><AppSelect value={isOperational ? "operational" : "non-operational"} onValueChange={value => setIsOperational(value === "operational")} ariaLabel={`Règle de calcul pour ${status.label}`} options={[{ value: "operational", label: "Compte comme actif" }, { value: "non-operational", label: "Hors actifs" }]} /><button disabled={update.isPending} className="inline-flex h-11 items-center justify-center border border-[#9dc7bb] bg-[#fffefa] px-3 text-sm font-bold text-[#0b625e] disabled:opacity-60" aria-label={`Enregistrer ${status.label}`}><Save size={16} /></button><button type="button" onClick={() => void archive()} disabled={remove.isPending || Boolean(status.usageCount)} className="inline-flex h-11 items-center justify-center border border-[#efc8c3] bg-[#fffefa] px-3 text-sm font-bold text-[#a1433d] disabled:cursor-not-allowed disabled:opacity-40" aria-label={`Archiver ${status.label}`}><Trash2 size={16} /></button></div><p className="mt-2 text-[11px] font-semibold text-[#63737d]">Utilisé par {status.usageCount ?? 0} dossier(s){status.usageCount ? " · archivage bloqué" : " · archivage autorisé"}.</p>{message ? <Feedback message={message} /> : null}</form>; }
function Feedback({ message }: { message: string }) { return <p className="mt-2 border-l-[3px] border-[#0b625e] bg-[#eaf5f0] p-2 text-xs font-semibold text-[#0b625e]">{message}</p>; }
