import { trpc } from "@/lib/trpc";
import { BookOpenCheck, FileSearch, FileUp, Layers3, ListTree, Pencil, Plus, RefreshCcw, RotateCcw, Save, Trash2, X } from "lucide-react";
import { type ChangeEvent, useEffect, useMemo, useState } from "react";
import { parseRcCatalogueExcel, type RcExcelPreview } from "./rc-excel-import";

type ImportMode = "merge" | "replace";
type FamilyDraft = { code: string; label: string };
type ActivityDraft = { code: string; label: string };
const emptyFamily: FamilyDraft = { code: "", label: "" };
const emptyActivity: ActivityDraft = { code: "", label: "" };

export function RcCatalogueManager() {
  const utils = trpc.useUtils();
  const summary = trpc.programSettings.rcCatalogue.summary.useQuery(undefined, { staleTime: 30_000 });
  const familiesQuery = trpc.programSettings.rcCatalogue.families.useQuery(undefined, { staleTime: 30_000 });
  const [query, setQuery] = useState("");
  const [selectedFamily, setSelectedFamily] = useState("");
  const activitiesInput = useMemo(() => ({ familyCode: selectedFamily || "000" }), [selectedFamily]);
  const activitiesQuery = trpc.programSettings.rcCatalogue.activities.useQuery(activitiesInput, { enabled: Boolean(selectedFamily), staleTime: 30_000 });
  const [preview, setPreview] = useState<RcExcelPreview | null>(null);
  const [mode, setMode] = useState<ImportMode>("merge");
  const [message, setMessage] = useState("");
  const [familyDraft, setFamilyDraft] = useState<FamilyDraft>(emptyFamily);
  const [activityDraft, setActivityDraft] = useState<ActivityDraft>(emptyActivity);
  const [familyEdit, setFamilyEdit] = useState<FamilyDraft | null>(null);
  const [activityEdit, setActivityEdit] = useState<ActivityDraft | null>(null);
  const normalized = query.trim().toLocaleLowerCase("fr");
  const families = useMemo(() => (familiesQuery.data ?? []).filter(family => !normalized || `${family.code} ${family.label}`.toLocaleLowerCase("fr").includes(normalized)).slice(0, 100), [familiesQuery.data, normalized]);

  useEffect(() => {
    if (!selectedFamily && familiesQuery.data?.[0]) setSelectedFamily(familiesQuery.data[0].code);
    if (selectedFamily && familiesQuery.data && !familiesQuery.data.some(family => family.code === selectedFamily)) setSelectedFamily(familiesQuery.data[0]?.code ?? "");
  }, [familiesQuery.data, selectedFamily]);

  const refresh = async () => { await Promise.all([utils.programSettings.rcCatalogue.summary.invalidate(), utils.programSettings.rcCatalogue.families.invalidate(), utils.programSettings.rcCatalogue.activities.invalidate(), utils.programSettings.rcCatalogue.archived.invalidate(), utils.programSettings.referenceRegistry.list.invalidate()]); };
  const merge = trpc.programSettings.rcCatalogue.mergeFromExcel.useMutation({ onSuccess: async result => { setMessage(`${result.activityCount} activité(s) et ${result.familyCount} catégorie(s) disponibles depuis ${result.sourceFilename}.`); setPreview(null); await refresh(); } });
  const replace = trpc.programSettings.rcCatalogue.replaceFromExcel.useMutation({ onSuccess: async result => { setMessage(`Catalogue remplacé : ${result.activityCount} activité(s) et ${result.familyCount} catégorie(s).`); setPreview(null); await refresh(); } });
  const reset = trpc.programSettings.rcCatalogue.resetToReference.useMutation({ onSuccess: async () => { setMessage("Le catalogue de référence est de nouveau utilisé."); await refresh(); } });
  const createFamily = trpc.programSettings.rcCatalogue.createFamily.useMutation({ onSuccess: async () => { setFamilyDraft(emptyFamily); setMessage("Catégorie RC ajoutée."); await refresh(); } });
  const updateFamily = trpc.programSettings.rcCatalogue.updateFamily.useMutation({ onSuccess: async () => { setFamilyEdit(null); setMessage("Catégorie RC modifiée."); await refresh(); } });
  const archiveFamily = trpc.programSettings.rcCatalogue.archiveFamily.useMutation({ onSuccess: async () => { setMessage("Catégorie RC archivée pendant 30 jours."); await refresh(); } });
  const createActivity = trpc.programSettings.rcCatalogue.createActivity.useMutation({ onSuccess: async () => { setActivityDraft(emptyActivity); setMessage("Activité RC ajoutée."); await refresh(); } });
  const updateActivity = trpc.programSettings.rcCatalogue.updateActivity.useMutation({ onSuccess: async () => { setActivityEdit(null); setMessage("Activité RC modifiée."); await refresh(); } });
  const archiveActivity = trpc.programSettings.rcCatalogue.archiveActivity.useMutation({ onSuccess: async () => { setMessage("Activité RC archivée pendant 30 jours."); await refresh(); } });
  const pending = merge.isPending || replace.isPending || reset.isPending || createFamily.isPending || updateFamily.isPending || archiveFamily.isPending || createActivity.isPending || updateActivity.isPending || archiveActivity.isPending;
  const reportError = (error: unknown) => setMessage(error instanceof Error ? error.message : "Opération RC impossible.");

  const onFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = ""; if (!file) return;
    setMessage("");
    try { if (file.size > 8 * 1024 * 1024) throw new Error("Le fichier RC dépasse la limite de 8 Mo."); setPreview(parseRcCatalogueExcel(file.name, await file.arrayBuffer())); } catch (error) { setPreview(null); reportError(error); }
  };
  const commit = async () => { if (!preview) return; setMessage(""); try { if (mode === "merge") await merge.mutateAsync(preview); else await replace.mutateAsync(preview); } catch (error) { reportError(error); } };
  const saveFamily = async () => { try { if (familyEdit) await updateFamily.mutateAsync(familyEdit); else await createFamily.mutateAsync(familyDraft); } catch (error) { reportError(error); } };
  const saveActivity = async () => { if (!selectedFamily) return; try { if (activityEdit) await updateActivity.mutateAsync(activityEdit); else await createActivity.mutateAsync({ familyCode: selectedFamily, ...activityDraft }); } catch (error) { reportError(error); } };

  return <section className="space-y-5">
    <div className="ui-sheet flex items-start gap-3 p-5 sm:p-6"><span className="grid h-10 w-10 shrink-0 place-items-center border border-[#b8d2c7] bg-[#eaf3ee] text-[#0b625e]"><BookOpenCheck size={19} /></span><div><p className="ui-label">Nomenclature d’activité</p><h2 className="mt-2 font-serif text-3xl text-[#182b3a]">Registre de commerce</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#63737d]">Ajoutez, renommez ou archivez les catégories et activités de votre cabinet. L’import Excel reste disponible pour une mise à jour en masse.</p></div></div>
    <section className="ui-sheet p-5 sm:p-6"><div className="grid grid-cols-3 gap-px border border-[#d8e2dc] bg-[#d8e2dc]"><Metric label="Catégories" value={String(summary.data?.familyCount ?? 0)} /><Metric label="Activités" value={String(summary.data?.activityCount ?? 0)} tone="teal" /><Metric label="Source" value={summary.data?.isCustom ? "Cabinet" : "Base"} /></div><div className="mt-5 flex flex-col gap-3 border-y border-[#dce3dc] py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[#182b3a]">{summary.data?.isCustom ? "Catalogue administré par le cabinet" : "Catalogue de référence du programme"}</p><p className="mt-1 text-xs text-[#63737d]">{summary.data?.sourceFilename ? `${summary.data.sourceFilename} · ` : ""}{summary.data?.importedAt ? new Date(summary.data.importedAt).toLocaleDateString("fr-DZ") : "Une première modification crée votre copie de travail."}</p></div><button type="button" disabled={pending || !summary.data?.isCustom} onClick={() => void reset.mutateAsync().catch(reportError)} className="inline-flex h-10 items-center justify-center gap-2 border border-[#d7bcb7] px-3 text-xs font-bold text-[#9b463f] disabled:opacity-40"><RotateCcw size={15} /> Réinitialiser</button></div>
      <label className="mt-5 flex h-11 items-center gap-2 border border-[#c7d8d3] bg-white px-3 text-[#63737d]"><FileSearch size={17} className="text-[#0b625e]" /><input value={query} onChange={event => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm text-[#182b3a] outline-none" placeholder="Rechercher une catégorie RC…" /></label>
      <div className="mt-4 grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.35fr)]"><div><div className="max-h-[29rem] overflow-y-auto border-y border-[#dce3dc]">{families.map(family => <div key={family.code} className={`grid grid-cols-[4rem_minmax(0,1fr)_auto] gap-2 border-b border-[#e7ece8] px-2 py-3 last:border-b-0 ${selectedFamily === family.code ? "bg-[#eff7f3]" : ""}`}><button type="button" onClick={() => setSelectedFamily(family.code)} className="text-left font-serif text-lg text-[#0b625e]">{family.code}</button><button type="button" onClick={() => setSelectedFamily(family.code)} className="min-w-0 text-left text-sm font-bold text-[#182b3a]">{family.label}<span className="mt-1 block text-xs font-medium text-[#63737d]">{family.activityCount} activité(s)</span></button><span className="flex items-center gap-1"><button type="button" aria-label={`Modifier ${family.label}`} onClick={() => setFamilyEdit({ code: family.code, label: family.label })} className="grid h-8 w-8 place-items-center text-[#0b625e] hover:bg-[#dfeee8]"><Pencil size={15} /></button><button type="button" aria-label={`Archiver ${family.label}`} onClick={() => void archiveFamily.mutateAsync({ code: family.code }).catch(reportError)} className="grid h-8 w-8 place-items-center text-[#9b463f] hover:bg-[#f9e8e4]"><Trash2 size={15} /></button></span></div>)}{!families.length ? <p className="p-4 text-sm text-[#63737d]">Aucune catégorie ne correspond.</p> : null}</div>
        <div className="mt-4 border-l-[3px] border-[#0b625e] bg-[#f4faf7] p-4"><p className="ui-label">{familyEdit ? "Modifier la catégorie" : "Nouvelle catégorie"}</p><div className="mt-3 grid gap-3 sm:grid-cols-[7rem_1fr_auto]"><input value={(familyEdit ?? familyDraft).code} onChange={event => familyEdit ? setFamilyEdit({ ...familyEdit, code: event.target.value.replace(/\D/g, "").slice(0, 3) }) : setFamilyDraft({ ...familyDraft, code: event.target.value.replace(/\D/g, "").slice(0, 3) })} disabled={Boolean(familyEdit)} placeholder="Code 000" className="h-11 border border-[#c7d8d3] bg-white px-3 text-sm text-[#182b3a] disabled:bg-[#e8efeb]" /><input value={(familyEdit ?? familyDraft).label} onChange={event => familyEdit ? setFamilyEdit({ ...familyEdit, label: event.target.value }) : setFamilyDraft({ ...familyDraft, label: event.target.value })} placeholder="Libellé de catégorie" className="h-11 border border-[#c7d8d3] bg-white px-3 text-sm text-[#182b3a]" /><span className="flex gap-2"><button type="button" onClick={() => void saveFamily()} disabled={pending} className="ui-action"><Save size={16} /> Enregistrer</button>{familyEdit ? <button type="button" onClick={() => setFamilyEdit(null)} className="grid h-11 w-11 place-items-center border border-[#c7d8d3] text-[#63737d]"><X size={17} /></button> : null}</span></div></div></div>
        <div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="ui-label">Activités de la catégorie</p><h3 className="mt-1 font-serif text-2xl text-[#182b3a]">{familiesQuery.data?.find(family => family.code === selectedFamily)?.label ?? "Choisissez une catégorie"}</h3></div><select value={selectedFamily} onChange={event => { setSelectedFamily(event.target.value); setActivityEdit(null); }} className="h-11 max-w-full border border-[#c7d8d3] bg-white px-3 text-sm text-[#182b3a] outline-none"><option value="">Catégorie RC</option>{familiesQuery.data?.map(family => <option key={family.code} value={family.code}>{family.code} — {family.label}</option>)}</select></div>
          <div className="mt-4 max-h-[19.2rem] overflow-y-auto border-y border-[#dce3dc]">{activitiesQuery.data?.map(activity => <div key={activity.code} className="grid grid-cols-[5.5rem_minmax(0,1fr)_auto] gap-2 border-b border-[#e7ece8] px-2 py-3 last:border-b-0"><span className="font-mono text-xs font-bold text-[#0b625e]">{activity.code}</span><span className="min-w-0 text-sm font-semibold text-[#182b3a]">{activity.label}</span><span className="flex items-center gap-1"><button type="button" aria-label={`Modifier ${activity.label}`} onClick={() => setActivityEdit({ code: activity.code, label: activity.label })} className="grid h-8 w-8 place-items-center text-[#0b625e] hover:bg-[#dfeee8]"><Pencil size={15} /></button><button type="button" aria-label={`Archiver ${activity.label}`} onClick={() => void archiveActivity.mutateAsync({ code: activity.code }).catch(reportError)} className="grid h-8 w-8 place-items-center text-[#9b463f] hover:bg-[#f9e8e4]"><Trash2 size={15} /></button></span></div>)}{selectedFamily && !activitiesQuery.data?.length ? <p className="p-4 text-sm text-[#63737d]">Aucune activité active dans cette catégorie.</p> : null}</div>
          <div className="mt-4 border-l-[3px] border-[#0b625e] bg-[#f4faf7] p-4"><p className="ui-label">{activityEdit ? "Modifier l’activité" : "Nouvelle activité"}</p><div className="mt-3 grid gap-3 sm:grid-cols-[7.5rem_1fr_auto]"><input value={(activityEdit ?? activityDraft).code} onChange={event => activityEdit ? setActivityEdit({ ...activityEdit, code: event.target.value.replace(/\D/g, "").slice(0, 6) }) : setActivityDraft({ ...activityDraft, code: event.target.value.replace(/\D/g, "").slice(0, 6) })} disabled={Boolean(activityEdit)} placeholder="Code 000000" className="h-11 border border-[#c7d8d3] bg-white px-3 text-sm text-[#182b3a] disabled:bg-[#e8efeb]" /><input value={(activityEdit ?? activityDraft).label} onChange={event => activityEdit ? setActivityEdit({ ...activityEdit, label: event.target.value }) : setActivityDraft({ ...activityDraft, label: event.target.value })} placeholder="Libellé de l’activité" className="h-11 border border-[#c7d8d3] bg-white px-3 text-sm text-[#182b3a]" /><span className="flex gap-2"><button type="button" onClick={() => void saveActivity()} disabled={pending || !selectedFamily} className="ui-action"><Plus size={16} /> Enregistrer</button>{activityEdit ? <button type="button" onClick={() => setActivityEdit(null)} className="grid h-11 w-11 place-items-center border border-[#c7d8d3] text-[#63737d]"><X size={17} /></button> : null}</span></div></div>
        </div></div>
    </section>
    <section className="ui-sheet p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center border border-[#d9c483] bg-[#fff7df] text-[#87661e]"><FileUp size={19} /></span><div><p className="ui-label">Mise à jour en masse</p><h3 className="mt-2 font-serif text-3xl text-[#182b3a]">Importer un fichier Excel RC</h3><p className="mt-1 text-sm leading-6 text-[#63737d]">Chaque ligne doit comporter un code RC à six chiffres et un libellé dans la colonne suivante. Le remplacement est bloqué s’il rendrait une activité utilisée indisponible.</p></div></div><div className="mt-5 flex flex-col gap-3 lg:flex-row lg:items-end"><label className="flex min-w-0 flex-1 cursor-pointer items-center gap-3 border border-dashed border-[#8eb7aa] bg-[#f4faf7] p-4 text-sm font-bold text-[#0b625e] hover:bg-[#eaf6f1]"><FileUp size={18} /><span className="truncate">Choisir le fichier Excel ou CSV</span><input type="file" accept=".xlsx,.xls,.xlsb,.csv" onChange={event => void onFile(event)} className="sr-only" /></label><button type="button" onClick={() => void refresh()} disabled={pending} className="inline-flex h-11 items-center justify-center gap-2 border border-[#bfd4cc] bg-[#fffefa] px-4 text-sm font-bold text-[#0b625e]"><RefreshCcw size={16} /> Actualiser</button></div>{preview ? <div className="mt-5 border-l-[3px] border-[#0b625e] bg-[#f2f8f5] p-4"><p className="font-bold text-[#182b3a]">{preview.sourceFilename}</p><p className="mt-1 text-sm text-[#526872]">{preview.entries.length} activité(s) détectée(s) dans {preview.familyCount} catégorie(s).</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center"><AppMode value={mode} onChange={setMode} /><button type="button" onClick={() => void commit()} disabled={pending} className="ui-action"><Save size={17} />{pending ? "Importation…" : mode === "merge" ? "Ajouter / mettre à jour" : "Remplacer le catalogue"}</button></div></div> : null}{message ? <p className="mt-4 border-l-[3px] border-[#0b625e] bg-[#eaf5f0] p-3 text-sm font-semibold text-[#0b625e]">{message}</p> : null}</section>
  </section>;
}

function AppMode({ value, onChange }: { value: ImportMode; onChange: (value: ImportMode) => void }) { return <label className="text-sm font-bold text-[#425b64]">Mode d’import<select value={value} onChange={event => onChange(event.target.value as ImportMode)} className="ml-3 h-11 border border-[#bdd2ca] bg-white px-3 text-sm text-[#182b3a] outline-none"><option value="merge">Ajouter / mettre à jour</option><option value="replace">Remplacer complètement</option></select></label>; }
function Metric({ label, value, tone = "paper" }: { label: string; value: string; tone?: "paper" | "teal" }) { return <div className={`min-w-0 p-3 ${tone === "teal" ? "bg-[#0b625e] text-white" : "bg-[#fffefa] text-[#182b3a]"}`}><p className="truncate text-[9px] font-extrabold uppercase tracking-[.1em] opacity-70">{label}</p><p className="mt-1 truncate font-serif text-xl">{value}</p></div>; }
