/** Atelier fiscal moderne — gestion du profil et de la session du compte connecté. */

import { WorkspaceLayout, PageTitle } from "@/components/workspace-layout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

export function AccountPage() { const { user } = useAuth({ redirectOnUnauthenticated: true }); const utils = trpc.useUtils(); const [fullName, setFullName] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const profile = trpc.account.updateProfile.useMutation({ onSuccess: account => utils.account.me.setData(undefined, account) }); const password = trpc.account.changePassword.useMutation(); useEffect(() => setFullName(user?.fullName ?? ""), [user?.fullName]); const submitProfile = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await profile.mutateAsync({ fullName }); setMessage("Nom du compte mis à jour."); } catch (error) { setMessage(error instanceof Error ? error.message : "Mise à jour impossible."); } }; const submitPassword = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { await password.mutateAsync({ currentPassword, newPassword }); setCurrentPassword(""); setNewPassword(""); setMessage("Mot de passe modifié."); } catch (error) { setMessage(error instanceof Error ? error.message : "Modification impossible."); } };
  return <WorkspaceLayout><PageTitle eyebrow="Compte et session" title="Mon compte" description="Gérez les informations de votre espace comptable et votre accès sécurisé." /><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border border-[#d5dfdc] bg-white p-6"><div className="flex items-center gap-3"><UserRound className="text-[#0f766e]" /><h2 className="font-serif text-3xl">Profil</h2></div><form onSubmit={submitProfile} className="mt-6 space-y-4"><label className="block text-sm font-bold">Nom complet<input value={fullName} onChange={e => setFullName(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#d5dfdc] px-3 font-normal" /></label><label className="block text-sm font-bold">E-mail<input value={user?.email ?? ""} disabled className="mt-2 h-11 w-full rounded-lg border border-[#e3e9e7] bg-[#f4f7f6] px-3 font-normal text-[#627785]" /></label><button disabled={profile.isPending} className="rounded-lg bg-[#0f766e] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">Enregistrer le profil</button></form></section><section className="rounded-xl border border-[#d5dfdc] bg-white p-6"><div className="flex items-center gap-3"><KeyRound className="text-[#0f766e]" /><h2 className="font-serif text-3xl">Mot de passe</h2></div><form onSubmit={submitPassword} className="mt-6 space-y-4"><label className="block text-sm font-bold">Mot de passe actuel<input value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required type="password" className="mt-2 h-11 w-full rounded-lg border border-[#d5dfdc] px-3 font-normal" /></label><label className="block text-sm font-bold">Nouveau mot de passe<input value={newPassword} onChange={e => setNewPassword(e.target.value)} required minLength={10} type="password" className="mt-2 h-11 w-full rounded-lg border border-[#d5dfdc] px-3 font-normal" placeholder="10 caractères minimum" /></label><button disabled={password.isPending} className="rounded-lg bg-[#102a43] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">Modifier le mot de passe</button></form></section></div><section className="mt-6 rounded-xl border border-[#c6ddd5] bg-[#e9f5f0] p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-[#0f766e]" /><div><h2 className="font-serif text-2xl">Session actuelle</h2><p className="mt-1 text-sm text-[#426c62]">Votre session est associée à ce navigateur. Utilisez « Se déconnecter » dans la barre latérale pour la fermer.</p></div></div></section>{message ? <p className="mt-5 rounded-lg bg-[#fff7df] p-3 text-sm font-bold text-[#795b1d]">{message}</p> : null}</WorkspaceLayout>; }
