/** Atelier fiscal moderne — gestion de plusieurs dossiers, tous rattachés au compte connecté. */

import { PageTitle, useWorkspaceClients, WorkspaceLayout } from "@/components/workspace-layout";
import { AppSelect } from "@/components/form/app-select";
import { useAuth } from "@/_core/hooks/useAuth";
import { downloadFichePdf } from "@/features/fiche/fiche-pdf";
import { OfficialPrintContent } from "@/features/fiche/official-print-content";
import { cashTotal, createClientDraft, formatDA, normalizeBundle, paymentTotal, type ClientDraft } from "@/lib/client-data";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowLeft, Check, ChevronRight, FileDown, FolderOpen, Plus, Printer, Save, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

const tabs = [{ slug: "fiche", label: "Fiche" }, { slug: "documents", label: "Documents" }, { slug: "conformite", label: "Conformité" }, { slug: "paiements", label: "Paiements" }, { slug: "coffre", label: "Accès" }, { slug: "impression", label: "Impression" }];
type LegacyClientDraft = Omit<ClientDraft, "client"> & { client: Omit<ClientDraft["client"], "initialBalance"> & { initialBalance: number } };

export function ClientsPage() { return <WorkspaceLayout><ClientsContent /></WorkspaceLayout>; }
function ClientsContent() { const { allClients, operationalStatusLabels, isLoading } = useWorkspaceClients(); const [query, setQuery] = useState(""); const shown = allClients.filter(client => !client.archivedAt && client.fullName.toLowerCase().includes(query.toLowerCase())); return <><PageTitle eyebrow="Portefeuille du compte" title="Dossiers clients" description="Retrouvez et ouvrez les dossiers associés uniquement à votre compte." action={<Link href="/clients/nouveau" className="inline-flex items-center gap-2 rounded-lg bg-[#0f766e] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#0b625d]"><Plus size={17} /> Nouveau client</Link>} /><div className="mb-5 flex max-w-xl items-center gap-2 rounded-lg border border-[#d5dfdc] bg-white px-3"><Search size={17} className="text-[#78909a]" /><input value={query} onChange={e => setQuery(e.target.value)} className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Rechercher un client…" /></div>{isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" aria-busy="true">{[1, 2, 3].map(item => <div key={item} className="h-40 rounded-xl border border-[#d5dfdc] bg-white/75" />)}</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map(client => <Link key={client.id} href={`/clients/${client.id}/fiche`} className="group rounded-xl border border-[#d5dfdc] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#0f766e]"><div className="flex items-start justify-between gap-3"><div><p className="font-serif text-2xl text-[#102a43]">{client.fullName}</p><p className="mt-1 text-sm text-[#627785]">{client.activity || "Activité à préciser"}</p></div><ChevronRight className="text-[#0f766e] transition group-hover:translate-x-1" size={19} /></div><div className="mt-6 flex items-center justify-between border-t border-[#edf1f0] pt-4 text-xs"><span className={`rounded-full px-2.5 py-1 font-bold ${operationalStatusLabels.includes(client.status ?? "") ? "bg-[#e6f3ed] text-[#0f766e]" : "bg-[#fff1ee] text-[#a1433d]"}`}>{client.status}</span><span className="font-semibold text-[#627785]">{client.commune || "Sans commune"}</span></div></Link>)}{shown.length === 0 ? <div className="col-span-full rounded-xl border border-dashed border-[#cbd9d5] bg-white p-10 text-center"><FolderOpen className="mx-auto text-[#0f766e]" /><p className="mt-4 font-serif text-2xl">Aucun dossier à afficher</p><p className="mt-2 text-sm text-[#627785]">Créez un nouveau client pour commencer le suivi.</p><Link href="/clients/nouveau" className="mt-5 inline-flex rounded-lg bg-[#0f766e] px-4 py-2.5 text-sm font-bold text-white">Créer un client</Link></div> : null}</div>}</>; }

function useDraft(clientId: number) { const query = trpc.clients.get.useQuery({ clientId }); const utils = trpc.useUtils(); const [draft, setDraft] = useState<LegacyClientDraft | null>(null); useEffect(() => { if (query.data) setDraft(normalizeBundle(query.data) as LegacyClientDraft); }, [query.data]); const save = trpc.clients.saveBundle.useMutation({ onSuccess: async () => { await Promise.all([utils.clients.get.invalidate({ clientId }), utils.clients.list.invalidate()]); } }); return { query, draft, setDraft, save }; }
function ClientLoadState({ error }: { error?: string }) { return <WorkspaceLayout><div className="mx-auto max-w-xl rounded-xl border border-[#d5dfdc] bg-white p-8 text-center"><p className="font-serif text-3xl text-[#102a43]">{error ? "Dossier indisponible" : "Chargement du dossier…"}</p><p className="mt-3 text-sm leading-6 text-[#627785]">{error || "Les informations sécurisées du client sont en cours de préparation."}</p><Link href="/clients" className="mt-6 inline-flex rounded-lg bg-[#0f766e] px-4 py-2.5 text-sm font-bold text-white">Retour aux dossiers</Link></div></WorkspaceLayout>; }
function updateAt<T>(items: T[], index: number, patch: Partial<T>) { return items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item); }
function DetailFrame({ clientId, active, children, onSave, pending }: { clientId: number; active: string; children: React.ReactNode; onSave?: () => void; pending?: boolean }) { return <WorkspaceLayout><div className="mb-7"><Link href="/clients" className="inline-flex items-center gap-2 text-sm font-bold text-[#0f766e] transition hover:text-[#0b625d]"><ArrowLeft size={16} strokeWidth={2.25} /> Dossiers clients</Link><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-[#0f766e]">Dossier client actif</p><h1 className="mt-2 font-serif text-4xl text-[#102a43]">Suivi du client</h1></div>{onSave ? <div className="flex flex-wrap gap-2"><Link href={`/transferts?clientId=${clientId}`} className="inline-flex h-10 items-center justify-center rounded-lg border border-[#cfdad7] bg-white px-4 text-sm font-bold text-[#102a43]">Exporter ce client</Link><button disabled={pending} onClick={onSave} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#0f766e] px-4 text-sm font-bold text-white disabled:opacity-60"><Save size={16} />{pending ? "Enregistrement…" : "Enregistrer"}</button></div> : null}</div><nav className="mt-5 flex gap-1 overflow-x-auto border-b border-[#d7e0df]">{tabs.map(tab => <Link key={tab.slug} href={`/clients/${clientId}/${tab.slug}`} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-bold ${active === tab.slug ? "border-[#0f766e] text-[#0f766e]" : "border-transparent text-[#627785] hover:text-[#102a43]"}`}>{tab.label}</Link>)}</nav></div>{children}</WorkspaceLayout>; }

export function ClientFichePage({ clientId }: { clientId: number }) { const { query, draft, setDraft, save } = useDraft(clientId); if (!draft) return <ClientLoadState error={query.error?.message} />; const setClient = (field: keyof ClientDraft["client"], value: string | number) => setDraft({ ...draft, client: { ...draft.client, [field]: value } }); const persist = () => save.mutate({ clientId, data: draft }); return <DetailFrame clientId={clientId} active="fiche" onSave={persist} pending={save.isPending}><div className="grid gap-5 xl:grid-cols-2"><FormCard title="1. Informations générales"><GridFields fields={[ ["Nom / raison sociale", "fullName"], ["Activité", "activity"], ["Forme juridique", "legalForm"], ["Type de client", "clientType"], ["Statut", "status"], ["Commune", "commune"], ["Contact", "contact"]]} values={draft.client} onChange={setClient} /></FormCard><FormCard title="2. Références fiscales et juridiques"><GridFields fields={[["NIF", "nif"], ["N° RC", "rc"], ["BP", "bp"], ["Article d’imposition", "taxArticle"], ["NIN", "nin"], ["Régime", "regime"]]} values={draft.client} onChange={setClient} /></FormCard><FormCard title="3. Solde et observations" className="xl:col-span-2"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Solde initial (DA)<input value={draft.client.initialBalance} onChange={e => setClient("initialBalance", Number(e.target.value))} type="number" className="mt-2 h-10 w-full rounded-lg border border-[#d5dfdc] px-3 font-normal" /></label><div className="rounded-lg bg-[#eef4f2] p-4"><p className="text-xs font-bold text-[#627785]">Versements saisis</p><p className="mt-1 text-xl font-extrabold">{formatDA(paymentTotal(draft))}</p></div><div className="rounded-lg bg-[#fff7df] p-4"><p className="text-xs font-bold text-[#795b1d]">Solde final</p><p className="mt-1 text-xl font-extrabold text-[#102a43]">{formatDA(draft.client.initialBalance - paymentTotal(draft))}</p></div></div><label className="mt-5 block text-sm font-bold">Observations<textarea value={draft.client.observations} onChange={e => setClient("observations", e.target.value)} className="mt-2 min-h-28 w-full rounded-lg border border-[#d5dfdc] p-3 font-normal" placeholder="Notes internes utiles à l’impression…" /></label></FormCard></div>{save.isSuccess ? <p className="mt-4 flex items-center gap-2 text-sm font-bold text-[#0f766e]"><Check size={16} /> Dossier enregistré.</p> : null}</DetailFrame>; }

export function ClientDocumentsPage({ clientId }: { clientId: number }) { const { draft, setDraft, save } = useDraft(clientId); if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>; return <DetailFrame clientId={clientId} active="documents" onSave={() => save.mutate({ clientId, data: draft })} pending={save.isPending}><RegisterTable headers={["Document", "Catégorie", "Statut", "Observation"]}>{draft.documents.map((item, index) => <tr key={`${item.label}-${index}`}><td className="font-bold">{item.label}</td><td className="text-[#627785]">{item.category}</td><td><AppSelect value={item.status} onValueChange={value => setDraft({ ...draft, documents: updateAt(draft.documents, index, { status: value as any }) })} options={[{ value: "À demander", label: "À demander" }, { value: "Reçu", label: "Reçu" }, { value: "À vérifier", label: "À vérifier" }, { value: "Non requis", label: "Non requis" }]} /></td><td><input value={item.note} onChange={e => setDraft({ ...draft, documents: updateAt(draft.documents, index, { note: e.target.value }) })} className="h-9 w-full rounded-md border border-[#d5dfdc] px-2 text-sm" placeholder="Précision" /></td></tr>)}</RegisterTable></DetailFrame>; }

export function ClientCompliancePage({ clientId }: { clientId: number }) { const { draft, setDraft, save } = useDraft(clientId); if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>; return <DetailFrame clientId={clientId} active="conformite" onSave={() => save.mutate({ clientId, data: draft })} pending={save.isPending}><RegisterTable headers={["Obligation", "Statut", "Note"]}>{draft.compliance.map((item, index) => <tr key={`${item.label}-${index}`}><td className="font-bold">{item.label}</td><td><AppSelect value={item.status} onValueChange={value => setDraft({ ...draft, compliance: updateAt(draft.compliance, index, { status: value as any }) })} options={[{ value: "À vérifier", label: "À vérifier" }, { value: "Conforme", label: "Conforme" }, { value: "À régulariser", label: "À régulariser" }]} /></td><td><input value={item.note} onChange={e => setDraft({ ...draft, compliance: updateAt(draft.compliance, index, { note: e.target.value }) })} className="h-9 w-full rounded-md border border-[#d5dfdc] px-2 text-sm" placeholder="Note" /></td></tr>)}</RegisterTable></DetailFrame>; }

export function ClientCasesPage({ clientId }: { clientId: number }) { const { draft, setDraft, save } = useDraft(clientId); if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>; return <DetailFrame clientId={clientId} active="dossiers" onSave={() => save.mutate({ clientId, data: draft })} pending={save.isPending}><RegisterTable headers={["Dossier", "Type", "Statut", "Note"]}>{draft.cases.map((item, index) => <tr key={`${item.label}-${index}`}><td className="font-bold">{item.label}</td><td>{item.caseType}</td><td><AppSelect value={item.status} onValueChange={value => setDraft({ ...draft, cases: updateAt(draft.cases, index, { status: value as any }) })} options={[{ value: "À préparer", label: "À préparer" }, { value: "En cours", label: "En cours" }, { value: "Terminé", label: "Terminé" }]} /></td><td><input value={item.note} onChange={e => setDraft({ ...draft, cases: updateAt(draft.cases, index, { note: e.target.value }) })} className="h-9 w-full rounded-md border border-[#d5dfdc] px-2 text-sm" placeholder="Note" /></td></tr>)}</RegisterTable></DetailFrame>; }

export function ClientPaymentsPage({ clientId }: { clientId: number }) { const { draft, setDraft, save } = useDraft(clientId); const [form, setForm] = useState({ paymentDate: new Date().toISOString().slice(0, 10), label: "", reference: "", amount: 0 }); if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>; const add = () => { if (form.label && form.amount) { setDraft({ ...draft, payments: [...draft.payments, form] }); setForm({ paymentDate: new Date().toISOString().slice(0, 10), label: "", reference: "", amount: 0 }); } }; return <DetailFrame clientId={clientId} active="paiements" onSave={() => save.mutate({ clientId, data: draft })} pending={save.isPending}><div className="mb-5 grid gap-3 rounded-xl border border-[#cfded9] bg-[#edf7f3] p-4 md:grid-cols-5"><input value={form.paymentDate} type="date" onChange={e => setForm({ ...form, paymentDate: e.target.value })} className="h-10 rounded-md border border-[#c7d8d3] bg-white px-2 text-sm" /><input value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} placeholder="Objet" className="h-10 rounded-md border border-[#c7d8d3] bg-white px-2 text-sm" /><input value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })} placeholder="Référence" className="h-10 rounded-md border border-[#c7d8d3] bg-white px-2 text-sm" /><input value={form.amount || ""} type="number" onChange={e => setForm({ ...form, amount: Number(e.target.value) })} placeholder="Montant" className="h-10 rounded-md border border-[#c7d8d3] bg-white px-2 text-sm" /><button onClick={add} className="rounded-md bg-[#0f766e] text-sm font-bold text-white">Ajouter</button></div><div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Solde initial" value={formatDA(draft.client.initialBalance)} tone="navy" /><Metric label="Versements" value={formatDA(paymentTotal(draft))} tone="teal" /><Metric label="Solde final" value={formatDA(draft.client.initialBalance - paymentTotal(draft))} tone="paper" /></div><RegisterTable headers={["Date", "Objet", "Référence", "Montant"]}>{draft.payments.map((item, index) => <tr key={index}><td>{item.paymentDate}</td><td className="font-bold">{item.label}</td><td>{item.reference || "—"}</td><td>{formatDA(item.amount)}</td></tr>)}</RegisterTable></DetailFrame>; }

export function ClientCashPage({ clientId }: { clientId: number }) { const { draft, setDraft, save } = useDraft(clientId); const [form, setForm] = useState<{ entryDate: string; label: string; direction: "Entrée" | "Sortie"; amount: number }>({ entryDate: new Date().toISOString().slice(0, 10), label: "", direction: "Entrée", amount: 0 }); if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>; const add = () => { if (form.label && form.amount) { setDraft({ ...draft, cashEntries: [...draft.cashEntries, form] }); setForm({ entryDate: new Date().toISOString().slice(0, 10), label: "", direction: "Entrée", amount: 0 }); } }; return <DetailFrame clientId={clientId} active="caisse" onSave={() => save.mutate({ clientId, data: draft })} pending={save.isPending}><div className="mb-5 grid gap-3 rounded-xl border border-[#d8e1d8] bg-[#fffaf0] p-4 md:grid-cols-5"><input value={form.entryDate} type="date" onChange={e => setForm({ ...form, entryDate: e.target.value })} className="h-10 rounded-md border border-[#ded7c5] bg-white px-2 text-sm" /><input value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} placeholder="Libellé" className="h-10 rounded-md border border-[#ded7c5] bg-white px-2 text-sm" /><AppSelect value={form.direction} onValueChange={value => setForm({ ...form, direction: value as "Entrée" | "Sortie" })} options={[{ value: "Entrée", label: "Entrée" }, { value: "Sortie", label: "Sortie" }]} /><input value={form.amount || ""} type="number" onChange={e => setForm({ ...form, amount: Number(e.target.value) })} placeholder="Montant" className="h-10 rounded-md border border-[#ded7c5] bg-white px-2 text-sm" /><button onClick={add} className="rounded-md bg-[#102a43] text-sm font-bold text-white">Ajouter</button></div><div className="mb-5"><Metric label="Solde de caisse" value={formatDA(cashTotal(draft))} tone="navy" /></div><RegisterTable headers={["Date", "Libellé", "Sens", "Montant"]}>{draft.cashEntries.map((item, index) => <tr key={index}><td>{item.entryDate}</td><td className="font-bold">{item.label}</td><td>{item.direction}</td><td>{formatDA(item.amount)}</td></tr>)}</RegisterTable></DetailFrame>; }

export function ClientPrintPage({ clientId }: { clientId: number }) {
  const { user } = useAuth({ redirectOnUnauthenticated: true });
  const { draft } = useDraft(clientId);
  if (!draft) return <WorkspaceLayout><p>Chargement…</p></WorkspaceLayout>;
  const openPrintDialog = () => window.print();
  return <DetailFrame clientId={clientId} active="impression">
    <div className="no-print mb-5 flex flex-wrap justify-end gap-3">{user?.preferredDocumentMode === "print" ? <><button onClick={openPrintDialog} className="inline-flex items-center gap-2 rounded-lg bg-[#102a43] px-4 py-2.5 text-sm font-bold text-white"><Printer size={17} /> Imprimer la fiche</button><button onClick={() => void downloadFichePdf(draft)} className="inline-flex items-center gap-2 rounded-lg border border-[#cfdad7] bg-white px-4 py-2.5 text-sm font-bold text-[#102a43]"><FileDown size={17} /> Télécharger le PDF</button></> : <><button onClick={() => void downloadFichePdf(draft)} className="inline-flex items-center gap-2 rounded-lg bg-[#102a43] px-4 py-2.5 text-sm font-bold text-white"><FileDown size={17} /> Télécharger le PDF</button><button onClick={openPrintDialog} className="inline-flex items-center gap-2 rounded-lg border border-[#cfdad7] bg-white px-4 py-2.5 text-sm font-bold text-[#102a43]"><Printer size={17} /> Imprimer la fiche</button></>}</div>
    <OfficialPrintContent draft={draft} />
  </DetailFrame>;
}


function FormCard({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-[#d5dfdc] bg-white p-5 ${className}`}><h2 className="border-l-[3px] border-[#0f766e] pl-3 text-sm font-extrabold text-[#102a43]">{title}</h2><div className="mt-5">{children}</div></section>; }
function GridFields({ fields, values, onChange }: { fields: [string, keyof ClientDraft["client"]][]; values: ClientDraft["client"]; onChange: (field: keyof ClientDraft["client"], value: string) => void }) { return <div className="grid gap-4 sm:grid-cols-2">{fields.map(([label, field]) => <label key={field} className="text-[11px] font-extrabold uppercase tracking-[0.07em] text-[#627785]">{label}<input value={String(values[field] ?? "")} onChange={e => onChange(field, e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#d5dfdc] px-3 text-sm font-normal normal-case tracking-normal text-[#102a43]" /></label>)}</div>; }
function RegisterTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="client-register overflow-x-auto rounded-xl border border-[#d5dfdc] bg-white"><table className="w-full min-w-[640px] border-separate border-spacing-0 text-left text-sm"><thead><tr className="border-b-2 border-[#cfdad7] text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#627785]">{headers.map(header => <th key={header} className="bg-[#f7faf8] px-4 py-3.5 first:rounded-tl-xl last:rounded-tr-xl">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Metric({ label, value, tone }: { label: string; value: string; tone: "navy" | "teal" | "paper" }) { const tones = { navy: "bg-[#102a43] text-white", teal: "bg-[#0f766e] text-white", paper: "bg-[#edf2f1] text-[#102a43]" }; return <div className={`rounded-xl p-5 ${tones[tone]}`}><p className="text-xs font-bold opacity-75">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p></div>; }
function PrintSection({ title, values }: { title: string; values: string[][] }) { return <section className="mt-8"><h2 className="border-l-[3px] border-[#c99a3e] pl-3 text-sm font-extrabold uppercase tracking-[0.1em] text-[#102a43]">{title}</h2><div className="mt-4 grid gap-x-8 gap-y-3 sm:grid-cols-2">{values.map(([label, value]) => <div key={label} className="border-b border-[#e0e8e5] pb-2"><p className="text-[10px] font-extrabold uppercase tracking-[0.08em] text-[#627785]">{label}</p><p className="mt-1 text-sm font-semibold text-[#102a43]">{value || "—"}</p></div>)}</div></section>; }
