/** Route légère de transfert : état et orchestration, panneaux dans features/transfers. */
import { useAuth } from "@/_core/hooks/useAuth";
import { PageTitle, WorkspaceLayout } from "@/components/workspace-layout";
import { parseTransferImport, type ImportPayload } from "@/features/transfers/import-parser";
import { ExportPanel, ImportPanel, TransferSecurityNotice } from "@/features/transfers/transfer-panels";
import { normalizeBundle } from "@/lib/client-data";
import { trpc } from "@/lib/trpc";
import { ChangeEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";

type ExportPayload = { schemaVersion: 1; exportedAt: string; clients: unknown[] };
export const parseImport = parseTransferImport;

async function download(data: ExportPayload, format: "json" | "xlsx") { const date = new Date().toISOString().slice(0, 10); const clients = data.clients.map(normalizeBundle); if (format === "json") { const archive = { schemaVersion: 1 as const, application: "Fiche Client Impôt", exportedAt: data.exportedAt, summary: { clientCount: clients.length, format: "JSON", note: "Archive réimportable. Les identifiants de compte ne sont jamais inclus." }, clients }; const blob = new Blob([JSON.stringify(archive, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `fiche-client-archive-${date}.json`; link.click(); URL.revokeObjectURL(url); return; } const { downloadStyledExcelArchive } = await import("@/features/transfers/excel-archive"); downloadStyledExcelArchive(data); }

export function TransfersPage() { const { user } = useAuth({ redirectOnUnauthenticated: true }); const [location] = useLocation(); const activeClientId = Number(new URLSearchParams(location.split("?")[1] ?? "").get("clientId")); const clientsQuery = trpc.clients.list.useQuery(); const utils = trpc.useUtils(); const [selected, setSelected] = useState<number[]>([]); const [format, setFormat] = useState<"json" | "xlsx">("xlsx"); const [payload, setPayload] = useState<ImportPayload | null>(null); const [fileName, setFileName] = useState(""); const [message, setMessage] = useState(""); const exportMutation = trpc.transfers.exportData.useMutation(); const preview = trpc.transfers.previewImport.useMutation(); const commit = trpc.transfers.commitImport.useMutation({ onSuccess: async ({ clientIds }) => { await utils.clients.list.invalidate(); setMessage(`${clientIds.length} dossier(s) importé(s) dans votre compte.`); setPayload(null); setFileName(""); } });
  useEffect(() => { if (Number.isInteger(activeClientId) && activeClientId > 0) setSelected([activeClientId]); }, [activeClientId]); useEffect(() => { if (user) setFormat(user.preferredExportFormat); }, [user?.preferredExportFormat]);
  const toggle = (id: number) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const exportScope = async (scope: "active" | "selected" | "all") => { setMessage(""); try { const clientIds = scope === "all" ? undefined : scope === "active" ? [activeClientId] : selected; const response = await exportMutation.mutateAsync({ format, scope, clientIds }); await download(response, format); setMessage(`${response.clients.length} dossier(s) exporté(s) dans une archive ${format.toUpperCase()} structurée.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Export impossible."); } };
  const onFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setMessage(""); try { if (file.size > 8 * 1024 * 1024) throw new Error("Le fichier dépasse la limite de 8 Mo."); const parsed = parseTransferImport(file.name, file.name.toLowerCase().endsWith(".json") ? await file.text() : await file.arrayBuffer()); const result = await preview.mutateAsync(parsed); setPayload(parsed); setFileName(file.name); setMessage(`${result.clientCount} client(s), ${result.documentCount} document(s) et ${result.paymentCount} paiement(s) détectés. Vérifiez puis confirmez l’import.`); } catch (error) { setPayload(null); setFileName(""); setMessage(error instanceof Error ? error.message : "Fichier non valide."); } };
  return <WorkspaceLayout><PageTitle eyebrow="Archives de votre compte" title="Importer et exporter" description="Créez des archives claires, structurées et réimportables, limitées exclusivement à votre cabinet." /><div className="grid gap-6 xl:grid-cols-2"><ExportPanel format={format} setFormat={setFormat} activeClientId={activeClientId} clients={clientsQuery.data ?? []} selected={selected} toggle={toggle} pending={exportMutation.isPending} onExport={scope => void exportScope(scope)} /><ImportPanel onFile={onFile} fileName={fileName} ready={Boolean(payload)} isImporting={commit.isPending} onCommit={() => payload && commit.mutate(payload)} /></div><TransferSecurityNotice />{message ? <p className="mt-4 rounded-lg bg-[#fff7df] p-3 text-sm font-bold text-[#795b1d]">{message}</p> : null}</WorkspaceLayout>; }
