/** Fiche identité du client : les choix fiscaux sont contraints et les finances restent dans le registre du cabinet. */

import { WorkspaceLayout } from "@/components/workspace-layout";
import { normalizeBundle, type ClientDraft } from "@/lib/client-data";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

const tabs = [{ slug: "fiche", label: "Fiche" }, { slug: "documents", label: "Documents" }, { slug: "conformite", label: "Conformité" }, { slug: "paiements", label: "Paiements" }, { slug: "impression", label: "Impression" }];

export function ClientFichePage({ clientId }: { clientId: number }) {
  const query = trpc.clients.get.useQuery({ clientId });
  const utils = trpc.useUtils();
  const [draft, setDraft] = useState<ClientDraft | null>(null);
  useEffect(() => { if (query.data) setDraft(normalizeBundle(query.data)); }, [query.data]);
  const save = trpc.clients.saveBundle.useMutation({ onSuccess: () => void Promise.all([utils.clients.get.invalidate({ clientId }), utils.clients.list.invalidate()]) });
  if (!draft) return <WorkspaceLayout><div className="mx-auto max-w-5xl space-y-5" aria-busy="true"><div className="h-4 w-28 rounded bg-[#dfe9e5]" /><div className="h-12 w-2/5 rounded bg-[#e3ebe8]" /><div className="grid gap-5 xl:grid-cols-2"><div className="h-80 rounded-xl border border-[#d5dfdc] bg-white/75" /><div className="h-80 rounded-xl border border-[#d5dfdc] bg-white/75" /></div></div></WorkspaceLayout>;
  const setClient = (field: keyof ClientDraft["client"], value: string) => setDraft({ ...draft, client: { ...draft.client, [field]: value } });
  const saveDraft = () => save.mutate({ clientId, data: draft });
  return <WorkspaceLayout><div className="mb-7"><Link href="/clients" className="inline-flex items-center gap-2 text-sm font-bold text-[#0f766e]"><ArrowLeft size={16} /> Dossiers clients</Link><div className="mt-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-[#0f766e]">Dossier client actif</p><h1 className="mt-2 font-serif text-4xl text-[#102a43]">Fiche du client</h1></div><div className="flex flex-wrap gap-2"><Link href={`/transferts?clientId=${clientId}`} className="inline-flex h-10 items-center justify-center rounded-lg border border-[#cfdad7] bg-white px-4 text-sm font-bold text-[#102a43]">Exporter ce client</Link><button disabled={save.isPending} onClick={saveDraft} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#0f766e] px-4 text-sm font-bold text-white disabled:opacity-60"><Save size={16} />{save.isPending ? "Enregistrement…" : "Enregistrer"}</button></div></div><nav className="mt-5 flex gap-1 overflow-x-auto border-b border-[#d7e0df]">{tabs.map(tab => <Link key={tab.slug} href={`/clients/${clientId}/${tab.slug}`} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-bold ${tab.slug === "fiche" ? "border-[#0f766e] text-[#0f766e]" : "border-transparent text-[#627785] hover:text-[#102a43]"}`}>{tab.label}</Link>)}</nav></div><div className="grid gap-5 xl:grid-cols-2"><FormCard title="1. Informations générales"><TextGrid draft={draft} onChange={setClient} fields={[ ["Nom / raison sociale", "fullName"], ["Activité", "activity"], ["Commune", "commune"], ["Contact", "contact"] ]} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><SelectField label="Forme juridique" value={draft.client.legalForm} onChange={value => setClient("legalForm", value)} choices={["Personne physique", "Personne morale"]} /><SelectField label="Type de client" value={draft.client.clientType} onChange={value => setClient("clientType", value)} choices={["Nouveau client", "Ancien client"]} /><SelectField label="Statut" value={draft.client.status} onChange={value => setClient("status", value)} choices={["Actif", "Radié"]} /></div></FormCard><FormCard title="2. Références fiscales et juridiques"><TextGrid draft={draft} onChange={setClient} fields={[["NIF", "nif"], ["N° RC", "rc"], ["BP", "bp"], ["Article d’imposition", "taxArticle"], ["NIN", "nin"]]} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><SelectField label="Régime fiscal" value={draft.client.regime} onChange={value => setClient("regime", value)} choices={["Régime réel", "Régime réel simplifié", "Régime IFU"]} /><SelectField label="Centre d’impôt" value={draft.client.taxCenter} onChange={value => setClient("taxCenter", value)} choices={["CDI", "CPI"]} /></div></FormCard></div>{save.isSuccess ? <p className="mt-4 flex items-center gap-2 text-sm font-bold text-[#0f766e]"><Check size={16} /> Fiche enregistrée.</p> : null}</WorkspaceLayout>;
}

function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[#d5dfdc] bg-white p-5"><h2 className="border-l-[3px] border-[#0f766e] pl-3 text-sm font-extrabold text-[#102a43]">{title}</h2><div className="mt-5">{children}</div></section>; }
function TextGrid({ draft, onChange, fields }: { draft: ClientDraft; onChange: (field: keyof ClientDraft["client"], value: string) => void; fields: [string, keyof ClientDraft["client"]][] }) { return <div className="grid gap-4 sm:grid-cols-2">{fields.map(([label, field]) => <label key={field} className="text-[11px] font-extrabold uppercase tracking-[0.07em] text-[#627785]">{label}<input value={String(draft.client[field] ?? "")} onChange={event => onChange(field, event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#d5dfdc] px-3 text-sm font-normal normal-case tracking-normal text-[#102a43]" /></label>)}</div>; }
function SelectField({ label, value, choices, onChange }: { label: string; value: string; choices: string[]; onChange: (value: string) => void }) { return <label className="text-[11px] font-extrabold uppercase tracking-[0.07em] text-[#627785]">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#d5dfdc] bg-white px-3 text-sm font-bold normal-case tracking-normal text-[#102a43]">{choices.map(choice => <option key={choice}>{choice}</option>)}</select></label>; }
