/** Création de dossier séparée de la liste du portefeuille. */

import { PageTitle, WorkspaceLayout } from "@/components/workspace-layout";
import { ClientDraft, createClientDraft } from "@/lib/client-data";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, UserPlus } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";

type ClientStartForm = Pick<ClientDraft["client"], "fullName" | "activity" | "legalForm" | "clientType" | "status" | "regime" | "taxCenter" | "commune" | "contact">;

export function NewClientPage() {
  const [, setLocation] = useLocation();
  const [form, setForm] = useState<ClientStartForm>({ fullName: "", activity: "", legalForm: "Personne physique", clientType: "Nouveau client", status: "Actif", regime: "Régime réel", taxCenter: "CDI", commune: "", contact: "" });
  const create = trpc.clients.create.useMutation({ onSuccess: ({ clientId }) => setLocation(`/clients/${clientId}/fiche`) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.fullName.trim()) return; create.mutate({ ...createClientDraft(form.fullName.trim()).client, ...form, fullName: form.fullName.trim() }); };
  const textField = (key: "fullName" | "activity" | "commune" | "contact", label: string, placeholder: string) => <label className="text-sm font-bold text-[#30505d]">{label}<input value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} className="mt-2 h-11 w-full rounded-lg border border-[#d5dfdc] bg-white px-3 font-normal outline-none focus:border-[#0f766e]" placeholder={placeholder} /></label>;
  const selectField = <K extends "legalForm" | "clientType" | "status" | "regime" | "taxCenter">(key: K, label: string, choices: ClientStartForm[K][]) => <label className="text-sm font-bold text-[#30505d]">{label}<select value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value as ClientStartForm[K] })} className="mt-2 h-11 w-full rounded-lg border border-[#d5dfdc] bg-white px-3 font-normal outline-none focus:border-[#0f766e]">{choices.map(choice => <option key={choice} value={choice}>{choice}</option>)}</select></label>;
  return <WorkspaceLayout><PageTitle eyebrow="Nouveau dossier" title="Créer un client" description="Commencez par les informations essentielles. Toutes les autres rubriques peuvent être complétées ensuite dans la fiche." action={<Link href="/clients" className="inline-flex items-center gap-2 rounded-lg border border-[#cfdad7] bg-white px-4 py-2.5 text-sm font-bold text-[#102a43]"><ArrowLeft size={17} /> Dossiers clients</Link>} /><form onSubmit={submit} className="mx-auto max-w-4xl rounded-2xl border border-[#d5dfdc] bg-white p-6 shadow-[0_12px_32px_rgba(16,42,67,0.05)] sm:p-8"><div className="flex items-start gap-3 border-b border-[#e6eeeb] pb-6"><span className="rounded-xl bg-[#e8f4ef] p-3 text-[#0f766e]"><UserPlus size={22} /></span><div><h2 className="font-serif text-3xl text-[#102a43]">Informations de départ</h2><p className="mt-1 text-sm leading-6 text-[#627785]">Le dossier est créé uniquement dans votre compte sécurisé.</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-2">{textField("fullName", "Nom complet / raison sociale", "Nom du client ou de l’entreprise")}{textField("activity", "Activité", "Ex. Commerce, prestation, profession libérale")}{selectField("legalForm", "Forme juridique", ["Personne physique", "Personne morale"])}{selectField("clientType", "Type de client", ["Nouveau client", "Ancien client"])}{selectField("status", "Statut", ["Actif", "Radié"])}{selectField("regime", "Régime fiscal", ["Régime réel", "Régime réel simplifié", "Régime IFU"])}{selectField("taxCenter", "Centre d’impôt", ["CDI", "CPI"])}{textField("commune", "Commune", "Commune de rattachement")}{textField("contact", "Contact", "Téléphone ou e-mail professionnel")}</div><div className="mt-8 flex flex-col-reverse gap-3 border-t border-[#e6eeeb] pt-6 sm:flex-row sm:justify-end"><Link href="/clients" className="inline-flex h-11 items-center justify-center rounded-lg border border-[#cfdad7] bg-white px-5 text-sm font-bold text-[#526775]">Annuler</Link><button disabled={create.isPending || !form.fullName.trim()} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#0f766e] px-5 text-sm font-bold text-white disabled:opacity-60">{create.isPending ? "Création…" : "Créer et ouvrir la fiche"}<ArrowRight size={17} /></button></div>{create.error ? <p className="mt-4 rounded-lg bg-[#fff2ef] p-3 text-sm font-semibold text-[#a1433d]">{create.error.message}</p> : null}</form></WorkspaceLayout>;
}
