/** Contenu officiel A4 de la fiche, réutilisable pour impression et contrôle visuel. */

import { formatDA, paymentTotal, type ClientDraft } from "@/lib/client-data";

export function OfficialPrintContent({ draft }: { draft: ClientDraft }) {
  const received = draft.documents.filter(item => item.status === "Reçu");
  const initialBalance = Number(draft.client.initialBalance ?? 0);
  const printedContacts = draft.contacts.length ? draft.contacts.map(item => `${item.label || item.type} : ${item.value}`).join(" · ") : draft.client.contact;
  return <article className="print-sheet official-fiche mx-auto max-w-4xl rounded-xl border border-[#d5dfdc] bg-white p-7 shadow-[0_12px_35px_rgba(16,42,67,0.05)] sm:p-9"><header className="border-b-2 border-[#0f766e] pb-5"><div className="flex items-start justify-between gap-6"><div><p className="text-[9px] font-extrabold uppercase tracking-[0.16em] text-[#0f766e]">Dossier administratif confidentiel</p><h1 className="mt-2 font-serif text-4xl text-[#102a43]">Fiche de suivi fiscal</h1><p className="mt-1 text-xs text-[#627785]">Éditée le {new Intl.DateTimeFormat("fr-DZ", { dateStyle: "long" }).format(new Date())}</p></div><div className="rounded-lg bg-[#eef6f2] px-4 py-3 text-right"><p className="text-[9px] font-extrabold uppercase tracking-[0.1em] text-[#0f766e]">Statut du dossier</p><p className="mt-1 text-sm font-extrabold text-[#102a43]">{draft.client.status}</p></div></div></header><div className="mt-5 grid gap-x-8 gap-y-4 sm:grid-cols-2"><InfoSection title="Identité et activité" values={[["Nom / raison sociale", draft.client.fullName], ["Activité", draft.client.activity], ["Forme juridique", draft.client.legalForm], ["Type de client", draft.client.clientType], ["Commune", draft.client.commune], ["Contacts", printedContacts]]} /><InfoSection title="Références fiscales et sociales" values={[["NIF", draft.client.nif], ["N° RC", draft.client.rc], ["Article d’imposition", draft.client.taxArticle], ["NIN", draft.client.nin], ["Régime fiscal", draft.client.regime], ["Centre d’impôt", draft.client.taxCenter], ["Affilié à la CNAS", draft.client.cnasAffiliated ? "Oui" : "Non"], ["Affilié au CASNOS", draft.client.casnosAffiliated ? "Oui" : "Non"]]} /></div><section className="mt-5 break-inside-avoid"><h2 className="border-l-[3px] border-[#c99a3e] pl-3 text-[11px] font-extrabold uppercase tracking-[0.1em] text-[#102a43]">Paiements et observations</h2><div className="mt-3 grid grid-cols-3 gap-3"><Metric label="Solde initial" value={formatDA(initialBalance)} /><Metric label="Paiements" value={formatDA(paymentTotal(draft))} /><Metric label="Solde estimé" value={formatDA(initialBalance - paymentTotal(draft))} /></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-[#30505d]">{draft.client.observations || "Aucune observation financière renseignée."}</p></section><section className="mt-5 break-inside-avoid"><h2 className="border-l-[3px] border-[#c99a3e] pl-3 text-[11px] font-extrabold uppercase tracking-[0.1em] text-[#102a43]">Pièces reçues</h2><p className="mt-3 text-xs leading-5 text-[#30505d]">{received.length ? received.slice(0, 8).map(item => item.label).join(" · ") : "Aucune pièce marquée comme reçue."}</p></section><footer className="mt-6 flex justify-between border-t border-[#d7e0df] pt-4 text-[9px] text-[#627785]"><span>Fiche à vérifier avant transmission.</span><span>Signature / cachet</span></footer></article>;
}

function InfoSection({ title, values }: { title: string; values: [string, string][] }) { return <section className="break-inside-avoid"><h2 className="border-l-[3px] border-[#c99a3e] pl-3 text-[11px] font-extrabold uppercase tracking-[0.1em] text-[#102a43]">{title}</h2><dl className="mt-3 space-y-2">{values.map(([label, value]) => <div key={label} className="flex items-baseline justify-between gap-4 border-b border-[#edf1f0] pb-1.5"><dt className="text-[9px] font-bold uppercase tracking-[0.06em] text-[#627785]">{label}</dt><dd className="max-w-[60%] truncate text-right text-xs font-semibold text-[#102a43]">{value || "—"}</dd></div>)}</dl></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#f4f7f6] p-3"><p className="text-[9px] font-extrabold uppercase tracking-[0.08em] text-[#627785]">{label}</p><p className="mt-1 text-sm font-extrabold text-[#102a43]">{value}</p></div>; }
